@accentColor=#5856D6

# Softer, more modern component shapes
Button.arc=12
Component.arc=12
TextComponent.arc=10
ScrollBar.thumbArc=999
ScrollBar.width=10

# Breathing room inside inputs & buttons
Button.margin=6,16,6,16
Component.focusWidth=1
TextComponent.margin=4,8,4,8

# Quieter borders / dividers
Component.borderColor=#E2E2E8
SplitPaneDivider.gripDotCount=0


TitlePane.unifiedBackground=false
TitlePane.buttonSize=35,23